config/routes.rb
Rails.application.routes.draw do
  resources :recipes

  get 'new_recipe_name' => 'recipes#new_recipe_name'
  post 'new_recipe_name' => 'recipes#create_recipe_name'
  
  get 'new_recipe_code/:id' => 'recipes#new_recipe_code'
  put 'new_recipe_code/:id' => 'recipes#create_recipe_code'

  get 'edit_recipe_code/:id' => 'recipes#edit_recipe_code'
  put 'edit_recipe_code/:id' => 'recipes#update_recipe_code'

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  def new_recipe_name
    @recipe = Recipe.new
  end

  def new_recipe_code
    @recipe = set_recipe
  end 

  def create_recipe_name
    @recipe = Recipe.new
    @recipe.dishId = 9999;
    @recipe.name = recipe_params[:name]
    @recipe.description = recipe_params[:description]
    @recipe.recipeCode = ""

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to action:"create_recipe_code", id:@recipe.id}
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  def create_recipe_code
    @recipe = Recipe.find(params[:id])
    @recipe.recipeCode = params[:recipeCode].to_json
    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end   
  end  

  def edit_recipe_code
    @recipe = set_recipe
    @recipeCode = JSON.parse(@recipe.recipeCode)
  end

  def update_recipe_code
    @recipe = Recipe.find(params[:id])
    @recipe.recipeCode = params[:recipeCode].to_json
    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:name, :description, :dishId, :recipeCode, :openSource)
    end

    def recipe_code_params
      params.permit(:id, :"recipeCode")
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reciper</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<h1> Reciper </h1>

<%= yield %>

</body>
</html>

app/views/recipes/_form.html.erb
<%= form_for(@recipe) do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% @recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :dishId %><br>
    <%= f.number_field :dishId %>
  </div>
  <div class="field">
    <%= f.label :recipeCode %><br>
    <%= f.text_field :recipeCode %>
  </div>
  <div class="field">
    <%= f.label :openSource %><br>
    <%= f.check_box :openSource %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render 'form' %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<h1>Listing recipes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Dishid</th>
      <th>Recipecode</th>
      <th>Opensource</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recipes.each do |recipe| %>
      <tr>
        <td><%= recipe.name %></td>
        <td><%= recipe.description %></td>
        <td><%= recipe.dishId %></td>
        <td><%= recipe.recipeCode %></td>
        <td><%= recipe.openSource %></td>
        <td><%= link_to 'Show', recipe %></td>
        <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
        <td><%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recipe', new_recipe_path %>

app/views/recipes/new.html.erb
<h1>New recipe</h1>

<%= render 'form' %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/new_recipe_name.html.erb
<div class="top clearfix">
	<div class="fl"></div>
	<div class="fr">Create Recipe</div>
</div>

<section>
	<%= form_for(@recipe, url:new_recipe_name_path, :method => :post) do |f|%>
		<div class="form-box" style="padding:0">
			<div class="item"><label><span>Recipe Name</span><input name="recipe[name]" type="text"></label></div>
			<div class="item"><label><span>Description</span><textarea name="recipe[description]"></textarea></label></div>
			<div class="item"><input class="smt-btn" type="button" id="submit_recipe_name" value="Create Recipe Code"></div>
		</div>
	<% end %>
</section>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @recipe.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @recipe.description %>
</p>

<p>
  <strong>Dishid:</strong>
  <%= @recipe.dishId %>
</p>

<p>
  <strong>Recipecode:</strong>
  <%= @recipe.recipeCode %>
</p>

<p>
  <strong>Opensource:</strong>
  <%= @recipe.openSource %>
</p>

<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<%= link_to 'Back', recipes_path %>